AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - test/**/*
    - "*.gemspec"
    - Rakefile
    - Gemfile

Style/StringLiterals:
  EnforcedStyle: double_quotes

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/MethodLength:
  Max: 15
