AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - "*.gemspec"
    - "Gemfile"

Performance:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*"

ClassAndModuleChildren:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
