require: rubocop-performance
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - "*.gemspec"
    - "Gemfile"

Performance:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*"
