AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - spec/**/*
    - *.gemspec
    - Rakefile
    - Gemfile

Style/StringLiterals:
  EnforcedStyle: double_quotes

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/MethodLength:
  Max: 15
