language: ruby
script: "bundle exec rake test:coverage"
rvm:
  - 2.4.1
  - 2.4.0
  - ruby-head
  - jruby-9.1.12.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: jruby-9.1.12.0
    - rvm: ruby-head
branches:
  only:
    - master
addons:
  code_climate:
    repo_token:
